### ISSUE TITLE
Plugin can't handle even minor variations of comment

### ISSUE THREAD

**Issue by mummybot** [moczolaszlo/postcss-inline-comment#10]
Other than the exact home page example (a valid css property and unit commented with no space between // and property name e.g. `//height: 0;`) then I can't get this to work on any other permutation of comment.
1. `git clone git@github.com:moczolaszlo/postcss-inline-comment.git`
2. `cd postcss-inline-comment`
3. `npm install`
4. Create a test.js and style.css file as below.
5. `node test.js`

**test.js**

``` javascript
var fs = require('fs'),
    postcss = require('postcss'),
    inlineComment = require('./');

var css = fs.readFileSync('style.css', 'utf8');

var output = postcss()
       .use(inlineComment())
       .process(css).css;

console.log(output);
```
#### Works!

``` css
.foo {
    //margin: 0;
    padding: 0;
}

outputs

.foo {
    padding: 0;
}
```
#### Doesn't work :(

``` css
.foo {
    // margin: 0;
    padding: 0;
}

outputs

.foo {
    // margin: 0;
    padding: 0;
}
```

``` css
.foo {
    // Hello world
    background-color: red;
}

outputs

.foo {
    // Hello world
    background-color: red;
}
```

``` css
.foo {
    //Hello world
    background-color: red;
}

outputs

.foo {
}
```

``` css
.foo {
    //hello world;
    padding: 0;
}

/Volumes/Storage/Development/sites/postcss-inline-comment/node_modules/postcss/lib/lazy-result.js:177
        if (this.error) throw this.error;
                        ^
CssSyntaxError: <css input>:2:5: Unknown word
    at Input.error (/Volumes/Storage/Development/sites/postcss-inline-comment/node_modules/postcss/lib/input.js:61:22)
    at Parser.unknownWord (/Volumes/Storage/Development/sites/postcss-inline-comment/node_modules/postcss/lib/parser.js:457:26)
    at Parser.word (/Volumes/Storage/Development/sites/postcss-inline-comment/node_modules/postcss/lib/parser.js:174:14)
    at Parser.loop (/Volumes/Storage/Development/sites/postcss-inline-comment/node_modules/postcss/lib/parser.js:60:26)
    at parse (/Volumes/Storage/Development/sites/postcss-inline-comment/node_modules/postcss/lib/parse.js:26:12)
    at new LazyResult (/Volumes/Storage/Development/sites/postcss-inline-comment/node_modules/postcss/lib/lazy-result.js:61:24)
    at Processor.process (/Volumes/Storage/Development/sites/postcss-inline-comment/node_modules/postcss/lib/processor.js:34:16)
    at Object.<anonymous> (/Volumes/Storage/Development/sites/postcss-inline-comment/test.js:9:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Environment**
Node: v5.6.0
